### ISSUE TITLE
فایل users.json اولویت نیست

### ISSUE THREAD

**Issue by CIAHAT** [mmdzov/luIP-marzban#22]
سلام و عرض ادب
تشکر از اسکریپتی که تهیه کردید.
مشکلی که وجود داره اینه که یوزر های توی فایل users.json اولویت نیستن و اسکریپت فقط همون MAX_ALLOW_USERS فایل env رو ملاک قرار میده.
ممنون میشم رسیدگی کنید یا احیانا اگر راه حلی داره بفرمایید که تست کنم.

**Comment by tgyhtia** [comment]
اشتباهی وجود نداره از این بابت
حتما اسم هارو اشتباه مینویسید یا حروف بزرگ و کوچیک رعایت نمیکنید یا به اشتباه یوزر اضاف کردید تو فایل users.json و متوجه نیستید

**Comment by CIAHAT** [comment]
> اشتباهی وجود نداره از این بابت حتما اسم هارو اشتباه مینویسید یا حروف بزرگ و کوچیک رعایت نمیکنید یا به اشتباه یوزر اضاف کردید تو فایل users.json و متوجه نیستید

نسخه dev رو استفاده کردید؟
و اینکه api رو فعال کردید یا خیر؟
بقیه موارد رو درست انجام دادم
